os:
- linux

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.1snapshot
  - 7.2snapshot
  - 7.3snapshot
  - master

matrix:
  allow_failures:
    - php: master

before_install:
  - composer self-update
  - if [ ! -d $HOME/.phive ]; then mkdir $HOME/.phive ; fi
  - if [ ! -f $HOME/.phive/phive.phar ]; then ant getphive ; mv phive.phar $HOME/.phive ; fi
  - sudo cp $HOME/.phive/phive.phar /usr/local/bin/phive

cache:
  directories:
    - "$HOME/.phive"
    - "$HOME/.phive/phars"
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"
    - "$HOME/.gnupg"

install:
  - travis_retry composer install --no-interaction --prefer-source
  - phive --no-progress install --trust-gpg-keys 4AA394086372C20A,2A8299CE842DD38C,E82B2FB314E9906E

script: ./tools/phpunit

notifications:
  email: false

env:
  global:
    secure: v4ay9b86o/wwBaW+7k7HdB8M7drF274LEkh2SYmKz/vLauc5gbKsEeaoDTek9xAOfa3V/3FDBYecty/qfhjDeo1gIVmvoE4DEf2XjszwyWUqRJTucqT+C8cKxSkbc0b3C/Xw8KF1oaaJ/HMHr/iVk9Q1TOyjdijnoG/PF1CZeSA=
