os:
- linux
language: php
php:
- 7.1.26
- 7.2
- 7.3
- 7.1snapshot
- 7.2snapshot
- 7.3snapshot
- master
matrix:
  allow_failures:
  - php: master
before_install:
- composer self-update
- if [ ! -d $HOME/.phive ]; then mkdir $HOME/.phive ; fi
- if [ ! -f $HOME/.phive/phive.phar ]; then ant getphive ; mv phive.phar $HOME/.phive
  ; fi
- sudo cp $HOME/.phive/phive.phar /usr/local/bin/phive
cache:
  directories:
  - "$HOME/.phive"
  - "$HOME/.phive/phars"
  - "$HOME/.cache/composer"
  - "$HOME/.composer/cache"
  - "$HOME/.gnupg"
install:
- travis_retry composer install --no-interaction --prefer-source
- phive --no-progress install --trust-gpg-keys 4AA394086372C20A,2A8299CE842DD38C,E82B2FB314E9906E
script: "./tools/phpunit"
notifications:
  email: false
env:
  global:
    secure: ou+icphdwzdA9o9xVN/dQEAdos03LuP3CPNz6wzRwaqeHq4KEVOCMdPaVs9Gyf+YAqS/xMGx15TNE5QK7+y1PE9tn7hhBtDunNIZU9n4g1OeC06hjm4eMg+8CwTZlXlAiDuDa5TC18vMMXFpVxL8NxyNVM1AdCrDg95Mx4+7YQY=
